# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('biography', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
