# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('authors', models.ManyToManyField(to='authors.Authors')),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
    ]
