# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-08 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['book']},
        ),
    ]
